[package]
name = "amberlock-winsec"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
windows.workspace = true
serde.workspace = true
serde_json.workspace = true
bitflags.workspace = true