[package]
name = "amberlock-winsec"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell.workspace = true
tempfile.workspace = true
windows.workspace = true
rayon.workspace = true
walkdir.workspace = true
amberlock-types = { path = "../amberlock-types" }