[package]
name = "amberlock-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
tempfile.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
parking_lot.workspace = true
amberlock-types = { path = "../amberlock-types" }
