[package]
name = "amberlock-types"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
windows.workspace = true
thiserror.workspace = true
anyhow.workspace = true
bitflags.workspace = true